[build]
  command = "npm run build"
  publish = "client/dist"
  functions = "netlify/functions"
  installCommand = "npm install && npm install --prefix client --include=dev"

[build.environment]
  NPM_CONFIG_PRODUCTION = "false"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev --prefix client"
  targetPort = 5173
  port = 8888
  publish = "client/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
